{
  "error": {
    "service": {
      "generic": "An internal error has occurred.",
      "timeout": "{{classname}}:: Error connection timeout:: {{endpoint}}",
      "unauthorized": "You don't have permission to access the required resource",
      "networkError": "Connection error. It has not been possible connect to server.",
      "notFound": "Resource not found",
      "methodNotAllowed": "Resource method not allowed",
      "networkDisabled": "Your network is not available. Please, active it."
    }
  },
  "identification": {
    "title": "National ID",
    "subtitle": "Enter the National ID number of the person to be vetted.",
    "send": "SEND",
    "message": "national id number"
  },
  "message": {
    "title": "Process completed",
    "message": "The vetting process has been successfully completed",
    "start": "Start a new vet"
  },
  "back": {
    "title": "Starting Screen",
    "msg": "Cancel screen if trying to go back"
  },
  "scanner": {
    "error": "An error has occurred"
  }
}
